### ISSUE TITLE
Normalize returned value across platforms.

### ISSUE THREAD

**Issue by jamestalmage** [jonschlinkert/is-windows#2]
The documentation suggests this returns a `boolean`, yet it appears to return a function for every platform except the browser.

I would prefer it was just a boolean everywhere.

Either way, the documentation should be corrected to clarify what the actual return value is.

**Comment by jonschlinkert** [comment]
my apologies, thanks for catching it. I've looked at the readme many times and never noticed it. I especially feel bad since this is twice in one week that a project of mine caused an issue in nyc. sorry guys.

**Comment by jamestalmage** [comment]
No problem!

Any reason (other than backwards compatibility), that you don't just return the boolean? It appears that is what you do in the browser environment.

**Comment by jonschlinkert** [comment]
> Any reason (other than backwards compatibility), that you don't just return the boolean?

No, I'll man up on this one, I don't think there was a reason. It was an oversight that wasn't caught because I didn't do enough unit tests 

this is little consolation, but that's really unusual for my projects. I tend to go overboard with unit tests usually. I even remember having a bad feeling about not doing more tests on this one - so shame on me. fwiw, this is exactly the reason I started [doing this](https://github.com/jonschlinkert/to-list/blob/master/test.js#L8). which, seems like overkill, but we have proof that it's not! lol

I think the API should be consistent. after using this several times, I agree, it makes more sense to return a boolean.

**Comment by jonschlinkert** [comment]
thanks for being awesome about it too

**Comment by jamestalmage** [comment]
:+1: No worries!
